### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by huacayacauh**
Just a name consistence between two commands.

### CODE REVIEW

**Comment by peterjc** [comment]
Thanks - and I hope the script is useful to you.

**Comment by huacayacauh** [comment]
Your code is great, thanks! now I am fighting with github-pages: my 
local jekyll works well with the result of convert.py but when I push 
everything github-pages indicates a vague "build error" (my projet 
website is in the docs/ folder of the repo).

I don't know if you are interested, let me just say a word in case you 
have time to read and maybe know this error:
* I created a docs folder and activated github-pages, then choosed the 
minimal jekyll theme.
* I downloaded your convert.py
* changed the .git assert to ../.git because my github-pages root is in 
docs/ folder
* I skipped the parts about blocklist and usernames (I don't have access 
to the full mediawiki sources, only what my colleague has extracted, a 
mediawiki_dump.xml), instead I just created empty files with these 
names.
* running your script worked well, it created .md and .mediawiki files 
for each page of the original wiki
* I pushed every commit, it created a wiki folder
* then I created a _layouts folder (my local jekyll version searches by 
default in "_layouts" with a final "s", whereas ur readme says "_layout" 
in last section, I tried both) with empty templates wiki.html and 
tagpage.html).
* it works well with my local jekyll (no warning), but the build of 
github-pages after I push all files fails without precision.
* github docs are messy and not very precise, congrats for your 
achievement ;-)

Thanks again!

Best,
Kévin

Le 2017-05-03 22:05, Peter Cock a écrit :

**Comment by peterjc** [comment]
I think ``_layout`` is a typo, it probably should be ``_layouts``, I'll fix that.

When I last had trouble with GitHub Pages builds failing, it was due to them having updated Jekyll and it behaved differently to the version I was using. So I'd start by checking your local setup versions against theirs.

See also e.g. https://github.com/biopython/biopython.github.io/blob/master/.travis.yml where I'm using TravisCI to try to mimic the GitHub Pages build, using as close a setup to that documented via https://github.com/biopython/biopython.github.io/blob/master/Gemfile - the point here is to get more logging about why it fails compared to the minimal email from GitHub Pages, not to actually use the TravisCI output directly in any way.

Unfortunately I am not a Jekyll expert and getting my own pages working took a fair amount of trial and error.

**Comment by huacayacauh** [comment]
Thanks for your comments and pointers

Le 2017-05-04 11:27, Peter Cock a écrit :

**Comment by peterjc** [comment]
Also empty templates is probably not going to work, with 05fce8f6ba3525c9050905e91bfc1033c017e30a I've added links to real examples.

**Comment by huacayacauh** [comment]
Great, it works \o/
Again: many thanks!

Le 2017-05-04 12:23, Peter Cock a écrit :

**Comment by peterjc** [comment]
Oh good :)

**Pull request merged**
